### ISSUE TITLE
No waw file traceback

### ISSUE THREAD

**Issue by Athwale** [MajliTech/bootanimation-creator#7]
Hello,
I run into issues creating a zipfile.
This is the exact path:

```
i We will now go through setup procedure
i Value below should be declared like this: WIDTHxHEIGHT, for example: 1080x1920
? What resolution is your animation? >> 680x920
? At what FPS is your boot animation? >> 1
i Now we will add the first part of your boot animation.
i The possible types are:
 - p - This part wil play, but will stop when boot ended
 - c - this part will play, no matter what happens
? What type the first part should be? >> p
? How many times should this part be repeated? >> 5
? How many FRAMES should be delayd after this part? >> 0
i Possible media types are:
 - png: a series of PNG images. They must be named number by number (0000.png, 0001.png, 0002.png, ...)
 - ffmpeg: Files will be decoded from ffmpeg to png and audio format. You can specify whatever file as long as FFmpeg supports it.
? Which type of media do you want to add to your boot animation? >> png
Gtk-Message: 09:17:01.579: GtkDialog mapped without a transient parent. This is discouraged.
? Would you also like to include WAV for this part? (Y/N) >> N
i Not including audio for this part.
✓ Congrats! You have your first BootAnimation part!
? Do you want to add more parts? >> N
Warning: --confirm-overwrite is deprecated and will be removed in a future version of zenity. Ignoring.
Gtk-Message: 09:17:39.254: GtkDialog mapped without a transient parent. This is discouraged.
i Starting animation creation...
i 1/3: Generate desc.txt
i 2/3: Copy media to bc-tmp (or decode to PNGs)
Traceback (most recent call last):
  File "/home/other/reader/maker/bootanimation-creator/src/main.py", line 205, in <module>
    libba.decode_media(animations,specs)
  File "/home/other/reader/maker/bootanimation-creator/src/libba.py", line 76, in decode_media
    if i['path']['1']: print(f"libba: The specified audio file for part {i['part']} is invalid ({i['path'][1]}). Please choose a file ending with .wav.\nlibba: Skipping audio file for part nr {i['part']}")
       ~~~~~~~~~^^^^^
TypeError: list indices must be integers or slices, not str
```

The png files I have are like this, which I think is correct:
```
$ ls Boot\ animation/New/bootanimation/part0/
001.png  002.png  003.png  004.png  005.png  006.png
```

**Comment by Athwale** [comment]
https://github.com/MajliTech/bootanimation-creator/pull/8

**Comment by MajliTech** [comment]
I merged it, let me know if it works.

**Comment by Athwale** [comment]
It works. :)
